### PR TITLE
Fixed the params access on top on the code, 

### PR DESCRIPTION
**Pull request by Code-Crash**
example : params.ApplictionName access before assign the params

### CODE REVIEW

**Comment by dlhdesign** [comment]
Not sure this is really an issue; do you have a sample of where/how it fails?

(Note that "logger" is being defined as a function above the params, but it is not being triggered. By the time it triggers, the "params" object has been populated.

**Comment by Code-Crash** [comment]
When you are using deploy method and the logger is not exists as below
```
if (!logger) {
        logger = function (msg) {
               console.log( util.format( '[%s] %s', chalk.green( params.ApplicationName + '[' + params.EnvironmentName + ']' ), msg ) );
        };
}
```
In the above code you are using params and params is not assigned yet then it will throw an error as ApplicationName is not defined for params.

**Comment by dlhdesign** [comment]
Do you have a gist or other code sample that illustrates an error result?

**Comment by Code-Crash** [comment]
Right now I don't have as I did try this package long ago.

But as @jamiesoncj and @lorengreenfield like the PR, might be they have some snippet to reproduce it.

**Comment by chris-jamieson** [comment]
Apologies but similarly I no longer have the relevant codebase to test this against.

**Comment by Code-Crash** [comment]
@jamiesoncj No worries :) , let's just hold on this PR until someone tries it.

Thanks.

**Comment by dlhdesign** [comment]
It's a safe fix; I'll go ahead and merge it in.

**Pull request merged**
